[mypy]
python_version = 3.12
warn_unused_configs = True
explicit_package_bases = True
namespace_packages = True

[mypy-torchvision.*]
ignore_missing_imports = True

[mypy-onnxruntime.*]
ignore_missing_imports = True
